// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_desis.DesisEfCore;

#nullable disable

namespace apidesis.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EFDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_desis.DesisEfCore.DesisComment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("commentId"));

                    b.Property<int?>("DesisEntryid")
                        .HasColumnType("integer");

                    b.Property<int?>("DesisUserid")
                        .HasColumnType("integer");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("commentId");

                    b.HasIndex("DesisEntryid");

                    b.HasIndex("DesisUserid");

                    b.ToTable("desisComment");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("category")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("desisEntry");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisRating", b =>
                {
                    b.Property<int>("rateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rateId"));

                    b.Property<int?>("DesisEntryid")
                        .HasColumnType("integer");

                    b.Property<int?>("DesisUserid")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.HasKey("rateId");

                    b.HasIndex("DesisEntryid");

                    b.HasIndex("DesisUserid");

                    b.ToTable("desisRating");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("studentNumber")
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<string>("university")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("desisUser");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisComment", b =>
                {
                    b.HasOne("api_desis.DesisEfCore.DesisEntry", "DesisEntry")
                        .WithMany("DesisComments")
                        .HasForeignKey("DesisEntryid");

                    b.HasOne("api_desis.DesisEfCore.DesisUser", "DesisUser")
                        .WithMany("DesisComments")
                        .HasForeignKey("DesisUserid");

                    b.Navigation("DesisEntry");

                    b.Navigation("DesisUser");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisRating", b =>
                {
                    b.HasOne("api_desis.DesisEfCore.DesisEntry", "DesisEntry")
                        .WithMany("DesisRatings")
                        .HasForeignKey("DesisEntryid");

                    b.HasOne("api_desis.DesisEfCore.DesisUser", "DesisUser")
                        .WithMany("DesisRatings")
                        .HasForeignKey("DesisUserid");

                    b.Navigation("DesisEntry");

                    b.Navigation("DesisUser");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisEntry", b =>
                {
                    b.Navigation("DesisComments");

                    b.Navigation("DesisRatings");
                });

            modelBuilder.Entity("api_desis.DesisEfCore.DesisUser", b =>
                {
                    b.Navigation("DesisComments");

                    b.Navigation("DesisRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
